/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BestSellersRouteImport } from './routes/best-sellers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BagsIndexRouteImport } from './routes/bags.index'
import { Route as ClutchesIndexRouteImport } from './routes/clutches.index'
import { Route as JewelleryIndexRouteImport } from './routes/jewellery.index'
import { Route as OrderReferenceRouteImport } from './routes/order.$reference'
import { Route as BagsGymBagsIndexRouteImport } from './routes/bags.gym-bags.index'
import { Route as BagsGymBagsSlugRouteImport } from './routes/bags.gym-bags.$slug'
import { Route as BagsHandbagsIndexRouteImport } from './routes/bags.handbags.index'
import { Route as BagsHandbagsSlugRouteImport } from './routes/bags.handbags.$slug'
import { Route as BagsPartyBagsIndexRouteImport } from './routes/bags.party-bags.index'
import { Route as BagsPartyBagsSlugRouteImport } from './routes/bags.party-bags.$slug'
import { Route as BagsPotliBagsIndexRouteImport } from './routes/bags.potli-bags.index'
import { Route as BagsPotliBagsSlugRouteImport } from './routes/bags.potli-bags.$slug'
import { Route as BagsShoulderBagsIndexRouteImport } from './routes/bags.shoulder-bags.index'
import { Route as BagsShoulderBagsSlugRouteImport } from './routes/bags.shoulder-bags.$slug'
import { Route as BagsTravelBagsIndexRouteImport } from './routes/bags.travel-bags.index'
import { Route as BagsTravelBagsSlugRouteImport } from './routes/bags.travel-bags.$slug'
import { Route as ClutchesBridalIndexRouteImport } from './routes/clutches.bridal.index'
import { Route as ClutchesBridalSlugRouteImport } from './routes/clutches.bridal.$slug'
import { Route as ClutchesDesignerIndexRouteImport } from './routes/clutches.designer.index'
import { Route as ClutchesDesignerSlugRouteImport } from './routes/clutches.designer.$slug'
import { Route as ClutchesPartyIndexRouteImport } from './routes/clutches.party.index'
import { Route as ClutchesPartySlugRouteImport } from './routes/clutches.party.$slug'
import { Route as ClutchesPotliIndexRouteImport } from './routes/clutches.potli.index'
import { Route as ClutchesPotliSlugRouteImport } from './routes/clutches.potli.$slug'
import { Route as JewelleryBraceletsIndexRouteImport } from './routes/jewellery.bracelets.index'
import { Route as JewelleryBraceletsSlugRouteImport } from './routes/jewellery.bracelets.$slug'
import { Route as JewelleryEarringsIndexRouteImport } from './routes/jewellery.earrings.index'
import { Route as JewelleryEarringsSlugRouteImport } from './routes/jewellery.earrings.$slug'
import { Route as JewelleryJewellerySetsIndexRouteImport } from './routes/jewellery.jewellery-sets.index'
import { Route as JewelleryJewellerySetsSlugRouteImport } from './routes/jewellery.jewellery-sets.$slug'
import { Route as JewelleryNecklacesIndexRouteImport } from './routes/jewellery.necklaces.index'
import { Route as JewelleryNecklacesSlugRouteImport } from './routes/jewellery.necklaces.$slug'
import { Route as JewelleryPendantsIndexRouteImport } from './routes/jewellery.pendants.index'
import { Route as JewelleryPendantsSlugRouteImport } from './routes/jewellery.pendants.$slug'
import { Route as JewelleryRingsIndexRouteImport } from './routes/jewellery.rings.index'
import { Route as JewelleryRingsSlugRouteImport } from './routes/jewellery.rings.$slug'
import { Route as JewelleryWatchesIndexRouteImport } from './routes/jewellery.watches.index'
import { Route as JewelleryWatchesSlugRouteImport } from './routes/jewellery.watches.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSellersRoute = BestSellersRouteImport.update({
  id: '/best-sellers',
  path: '/best-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsIndexRoute = BagsIndexRouteImport.update({
  id: '/bags/',
  path: '/bags/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClutchesIndexRoute = ClutchesIndexRouteImport.update({
  id: '/clutches/',
  path: '/clutches/',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryIndexRoute = JewelleryIndexRouteImport.update({
  id: '/jewellery/',
  path: '/jewellery/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderReferenceRoute = OrderReferenceRouteImport.update({
  id: '/order/$reference',
  path: '/order/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsGymBagsIndexRoute = BagsGymBagsIndexRouteImport.update({
  id: '/bags/gym-bags/',
  path: '/bags/gym-bags/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsGymBagsSlugRoute = BagsGymBagsSlugRouteImport.update({
  id: '/bags/gym-bags/$slug',
  path: '/bags/gym-bags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsHandbagsIndexRoute = BagsHandbagsIndexRouteImport.update({
  id: '/bags/handbags/',
  path: '/bags/handbags/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsHandbagsSlugRoute = BagsHandbagsSlugRouteImport.update({
  id: '/bags/handbags/$slug',
  path: '/bags/handbags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsPartyBagsIndexRoute = BagsPartyBagsIndexRouteImport.update({
  id: '/bags/party-bags/',
  path: '/bags/party-bags/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsPartyBagsSlugRoute = BagsPartyBagsSlugRouteImport.update({
  id: '/bags/party-bags/$slug',
  path: '/bags/party-bags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsPotliBagsIndexRoute = BagsPotliBagsIndexRouteImport.update({
  id: '/bags/potli-bags/',
  path: '/bags/potli-bags/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsPotliBagsSlugRoute = BagsPotliBagsSlugRouteImport.update({
  id: '/bags/potli-bags/$slug',
  path: '/bags/potli-bags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsShoulderBagsIndexRoute = BagsShoulderBagsIndexRouteImport.update({
  id: '/bags/shoulder-bags/',
  path: '/bags/shoulder-bags/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsShoulderBagsSlugRoute = BagsShoulderBagsSlugRouteImport.update({
  id: '/bags/shoulder-bags/$slug',
  path: '/bags/shoulder-bags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsTravelBagsIndexRoute = BagsTravelBagsIndexRouteImport.update({
  id: '/bags/travel-bags/',
  path: '/bags/travel-bags/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagsTravelBagsSlugRoute = BagsTravelBagsSlugRouteImport.update({
  id: '/bags/travel-bags/$slug',
  path: '/bags/travel-bags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClutchesBridalIndexRoute = ClutchesBridalIndexRouteImport.update({
  id: '/clutches/bridal/',
  path: '/clutches/bridal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClutchesBridalSlugRoute = ClutchesBridalSlugRouteImport.update({
  id: '/clutches/bridal/$slug',
  path: '/clutches/bridal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClutchesDesignerIndexRoute = ClutchesDesignerIndexRouteImport.update({
  id: '/clutches/designer/',
  path: '/clutches/designer/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClutchesDesignerSlugRoute = ClutchesDesignerSlugRouteImport.update({
  id: '/clutches/designer/$slug',
  path: '/clutches/designer/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClutchesPartyIndexRoute = ClutchesPartyIndexRouteImport.update({
  id: '/clutches/party/',
  path: '/clutches/party/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClutchesPartySlugRoute = ClutchesPartySlugRouteImport.update({
  id: '/clutches/party/$slug',
  path: '/clutches/party/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClutchesPotliIndexRoute = ClutchesPotliIndexRouteImport.update({
  id: '/clutches/potli/',
  path: '/clutches/potli/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClutchesPotliSlugRoute = ClutchesPotliSlugRouteImport.update({
  id: '/clutches/potli/$slug',
  path: '/clutches/potli/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryBraceletsIndexRoute = JewelleryBraceletsIndexRouteImport.update({
  id: '/jewellery/bracelets/',
  path: '/jewellery/bracelets/',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryBraceletsSlugRoute = JewelleryBraceletsSlugRouteImport.update({
  id: '/jewellery/bracelets/$slug',
  path: '/jewellery/bracelets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryEarringsIndexRoute = JewelleryEarringsIndexRouteImport.update({
  id: '/jewellery/earrings/',
  path: '/jewellery/earrings/',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryEarringsSlugRoute = JewelleryEarringsSlugRouteImport.update({
  id: '/jewellery/earrings/$slug',
  path: '/jewellery/earrings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryJewellerySetsIndexRoute =
  JewelleryJewellerySetsIndexRouteImport.update({
    id: '/jewellery/jewellery-sets/',
    path: '/jewellery/jewellery-sets/',
    getParentRoute: () => rootRouteImport,
  } as any)
const JewelleryJewellerySetsSlugRoute =
  JewelleryJewellerySetsSlugRouteImport.update({
    id: '/jewellery/jewellery-sets/$slug',
    path: '/jewellery/jewellery-sets/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const JewelleryNecklacesIndexRoute = JewelleryNecklacesIndexRouteImport.update({
  id: '/jewellery/necklaces/',
  path: '/jewellery/necklaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryNecklacesSlugRoute = JewelleryNecklacesSlugRouteImport.update({
  id: '/jewellery/necklaces/$slug',
  path: '/jewellery/necklaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryPendantsIndexRoute = JewelleryPendantsIndexRouteImport.update({
  id: '/jewellery/pendants/',
  path: '/jewellery/pendants/',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryPendantsSlugRoute = JewelleryPendantsSlugRouteImport.update({
  id: '/jewellery/pendants/$slug',
  path: '/jewellery/pendants/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryRingsIndexRoute = JewelleryRingsIndexRouteImport.update({
  id: '/jewellery/rings/',
  path: '/jewellery/rings/',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryRingsSlugRoute = JewelleryRingsSlugRouteImport.update({
  id: '/jewellery/rings/$slug',
  path: '/jewellery/rings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryWatchesIndexRoute = JewelleryWatchesIndexRouteImport.update({
  id: '/jewellery/watches/',
  path: '/jewellery/watches/',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryWatchesSlugRoute = JewelleryWatchesSlugRouteImport.update({
  id: '/jewellery/watches/$slug',
  path: '/jewellery/watches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/best-sellers': typeof BestSellersRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/admin/': typeof AdminIndexRoute
  '/bags/': typeof BagsIndexRoute
  '/clutches/': typeof ClutchesIndexRoute
  '/jewellery/': typeof JewelleryIndexRoute
  '/bags/gym-bags/$slug': typeof BagsGymBagsSlugRoute
  '/bags/handbags/$slug': typeof BagsHandbagsSlugRoute
  '/bags/party-bags/$slug': typeof BagsPartyBagsSlugRoute
  '/bags/potli-bags/$slug': typeof BagsPotliBagsSlugRoute
  '/bags/shoulder-bags/$slug': typeof BagsShoulderBagsSlugRoute
  '/bags/travel-bags/$slug': typeof BagsTravelBagsSlugRoute
  '/clutches/bridal/$slug': typeof ClutchesBridalSlugRoute
  '/clutches/designer/$slug': typeof ClutchesDesignerSlugRoute
  '/clutches/party/$slug': typeof ClutchesPartySlugRoute
  '/clutches/potli/$slug': typeof ClutchesPotliSlugRoute
  '/jewellery/bracelets/$slug': typeof JewelleryBraceletsSlugRoute
  '/jewellery/earrings/$slug': typeof JewelleryEarringsSlugRoute
  '/jewellery/jewellery-sets/$slug': typeof JewelleryJewellerySetsSlugRoute
  '/jewellery/necklaces/$slug': typeof JewelleryNecklacesSlugRoute
  '/jewellery/pendants/$slug': typeof JewelleryPendantsSlugRoute
  '/jewellery/rings/$slug': typeof JewelleryRingsSlugRoute
  '/jewellery/watches/$slug': typeof JewelleryWatchesSlugRoute
  '/bags/gym-bags/': typeof BagsGymBagsIndexRoute
  '/bags/handbags/': typeof BagsHandbagsIndexRoute
  '/bags/party-bags/': typeof BagsPartyBagsIndexRoute
  '/bags/potli-bags/': typeof BagsPotliBagsIndexRoute
  '/bags/shoulder-bags/': typeof BagsShoulderBagsIndexRoute
  '/bags/travel-bags/': typeof BagsTravelBagsIndexRoute
  '/clutches/bridal/': typeof ClutchesBridalIndexRoute
  '/clutches/designer/': typeof ClutchesDesignerIndexRoute
  '/clutches/party/': typeof ClutchesPartyIndexRoute
  '/clutches/potli/': typeof ClutchesPotliIndexRoute
  '/jewellery/bracelets/': typeof JewelleryBraceletsIndexRoute
  '/jewellery/earrings/': typeof JewelleryEarringsIndexRoute
  '/jewellery/jewellery-sets/': typeof JewelleryJewellerySetsIndexRoute
  '/jewellery/necklaces/': typeof JewelleryNecklacesIndexRoute
  '/jewellery/pendants/': typeof JewelleryPendantsIndexRoute
  '/jewellery/rings/': typeof JewelleryRingsIndexRoute
  '/jewellery/watches/': typeof JewelleryWatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/best-sellers': typeof BestSellersRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/admin': typeof AdminIndexRoute
  '/bags': typeof BagsIndexRoute
  '/clutches': typeof ClutchesIndexRoute
  '/jewellery': typeof JewelleryIndexRoute
  '/bags/gym-bags/$slug': typeof BagsGymBagsSlugRoute
  '/bags/handbags/$slug': typeof BagsHandbagsSlugRoute
  '/bags/party-bags/$slug': typeof BagsPartyBagsSlugRoute
  '/bags/potli-bags/$slug': typeof BagsPotliBagsSlugRoute
  '/bags/shoulder-bags/$slug': typeof BagsShoulderBagsSlugRoute
  '/bags/travel-bags/$slug': typeof BagsTravelBagsSlugRoute
  '/clutches/bridal/$slug': typeof ClutchesBridalSlugRoute
  '/clutches/designer/$slug': typeof ClutchesDesignerSlugRoute
  '/clutches/party/$slug': typeof ClutchesPartySlugRoute
  '/clutches/potli/$slug': typeof ClutchesPotliSlugRoute
  '/jewellery/bracelets/$slug': typeof JewelleryBraceletsSlugRoute
  '/jewellery/earrings/$slug': typeof JewelleryEarringsSlugRoute
  '/jewellery/jewellery-sets/$slug': typeof JewelleryJewellerySetsSlugRoute
  '/jewellery/necklaces/$slug': typeof JewelleryNecklacesSlugRoute
  '/jewellery/pendants/$slug': typeof JewelleryPendantsSlugRoute
  '/jewellery/rings/$slug': typeof JewelleryRingsSlugRoute
  '/jewellery/watches/$slug': typeof JewelleryWatchesSlugRoute
  '/bags/gym-bags': typeof BagsGymBagsIndexRoute
  '/bags/handbags': typeof BagsHandbagsIndexRoute
  '/bags/party-bags': typeof BagsPartyBagsIndexRoute
  '/bags/potli-bags': typeof BagsPotliBagsIndexRoute
  '/bags/shoulder-bags': typeof BagsShoulderBagsIndexRoute
  '/bags/travel-bags': typeof BagsTravelBagsIndexRoute
  '/clutches/bridal': typeof ClutchesBridalIndexRoute
  '/clutches/designer': typeof ClutchesDesignerIndexRoute
  '/clutches/party': typeof ClutchesPartyIndexRoute
  '/clutches/potli': typeof ClutchesPotliIndexRoute
  '/jewellery/bracelets': typeof JewelleryBraceletsIndexRoute
  '/jewellery/earrings': typeof JewelleryEarringsIndexRoute
  '/jewellery/jewellery-sets': typeof JewelleryJewellerySetsIndexRoute
  '/jewellery/necklaces': typeof JewelleryNecklacesIndexRoute
  '/jewellery/pendants': typeof JewelleryPendantsIndexRoute
  '/jewellery/rings': typeof JewelleryRingsIndexRoute
  '/jewellery/watches': typeof JewelleryWatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/best-sellers': typeof BestSellersRoute
  '/blog': typeof BlogRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/admin/': typeof AdminIndexRoute
  '/bags/': typeof BagsIndexRoute
  '/clutches/': typeof ClutchesIndexRoute
  '/jewellery/': typeof JewelleryIndexRoute
  '/bags/gym-bags/$slug': typeof BagsGymBagsSlugRoute
  '/bags/handbags/$slug': typeof BagsHandbagsSlugRoute
  '/bags/party-bags/$slug': typeof BagsPartyBagsSlugRoute
  '/bags/potli-bags/$slug': typeof BagsPotliBagsSlugRoute
  '/bags/shoulder-bags/$slug': typeof BagsShoulderBagsSlugRoute
  '/bags/travel-bags/$slug': typeof BagsTravelBagsSlugRoute
  '/clutches/bridal/$slug': typeof ClutchesBridalSlugRoute
  '/clutches/designer/$slug': typeof ClutchesDesignerSlugRoute
  '/clutches/party/$slug': typeof ClutchesPartySlugRoute
  '/clutches/potli/$slug': typeof ClutchesPotliSlugRoute
  '/jewellery/bracelets/$slug': typeof JewelleryBraceletsSlugRoute
  '/jewellery/earrings/$slug': typeof JewelleryEarringsSlugRoute
  '/jewellery/jewellery-sets/$slug': typeof JewelleryJewellerySetsSlugRoute
  '/jewellery/necklaces/$slug': typeof JewelleryNecklacesSlugRoute
  '/jewellery/pendants/$slug': typeof JewelleryPendantsSlugRoute
  '/jewellery/rings/$slug': typeof JewelleryRingsSlugRoute
  '/jewellery/watches/$slug': typeof JewelleryWatchesSlugRoute
  '/bags/gym-bags/': typeof BagsGymBagsIndexRoute
  '/bags/handbags/': typeof BagsHandbagsIndexRoute
  '/bags/party-bags/': typeof BagsPartyBagsIndexRoute
  '/bags/potli-bags/': typeof BagsPotliBagsIndexRoute
  '/bags/shoulder-bags/': typeof BagsShoulderBagsIndexRoute
  '/bags/travel-bags/': typeof BagsTravelBagsIndexRoute
  '/clutches/bridal/': typeof ClutchesBridalIndexRoute
  '/clutches/designer/': typeof ClutchesDesignerIndexRoute
  '/clutches/party/': typeof ClutchesPartyIndexRoute
  '/clutches/potli/': typeof ClutchesPotliIndexRoute
  '/jewellery/bracelets/': typeof JewelleryBraceletsIndexRoute
  '/jewellery/earrings/': typeof JewelleryEarringsIndexRoute
  '/jewellery/jewellery-sets/': typeof JewelleryJewellerySetsIndexRoute
  '/jewellery/necklaces/': typeof JewelleryNecklacesIndexRoute
  '/jewellery/pendants/': typeof JewelleryPendantsIndexRoute
  '/jewellery/rings/': typeof JewelleryRingsIndexRoute
  '/jewellery/watches/': typeof JewelleryWatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/best-sellers'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/new-arrivals'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/order/$reference'
    | '/admin/'
    | '/bags/'
    | '/clutches/'
    | '/jewellery/'
    | '/bags/gym-bags/$slug'
    | '/bags/handbags/$slug'
    | '/bags/party-bags/$slug'
    | '/bags/potli-bags/$slug'
    | '/bags/shoulder-bags/$slug'
    | '/bags/travel-bags/$slug'
    | '/clutches/bridal/$slug'
    | '/clutches/designer/$slug'
    | '/clutches/party/$slug'
    | '/clutches/potli/$slug'
    | '/jewellery/bracelets/$slug'
    | '/jewellery/earrings/$slug'
    | '/jewellery/jewellery-sets/$slug'
    | '/jewellery/necklaces/$slug'
    | '/jewellery/pendants/$slug'
    | '/jewellery/rings/$slug'
    | '/jewellery/watches/$slug'
    | '/bags/gym-bags/'
    | '/bags/handbags/'
    | '/bags/party-bags/'
    | '/bags/potli-bags/'
    | '/bags/shoulder-bags/'
    | '/bags/travel-bags/'
    | '/clutches/bridal/'
    | '/clutches/designer/'
    | '/clutches/party/'
    | '/clutches/potli/'
    | '/jewellery/bracelets/'
    | '/jewellery/earrings/'
    | '/jewellery/jewellery-sets/'
    | '/jewellery/necklaces/'
    | '/jewellery/pendants/'
    | '/jewellery/rings/'
    | '/jewellery/watches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/best-sellers'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/new-arrivals'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/order/$reference'
    | '/admin'
    | '/bags'
    | '/clutches'
    | '/jewellery'
    | '/bags/gym-bags/$slug'
    | '/bags/handbags/$slug'
    | '/bags/party-bags/$slug'
    | '/bags/potli-bags/$slug'
    | '/bags/shoulder-bags/$slug'
    | '/bags/travel-bags/$slug'
    | '/clutches/bridal/$slug'
    | '/clutches/designer/$slug'
    | '/clutches/party/$slug'
    | '/clutches/potli/$slug'
    | '/jewellery/bracelets/$slug'
    | '/jewellery/earrings/$slug'
    | '/jewellery/jewellery-sets/$slug'
    | '/jewellery/necklaces/$slug'
    | '/jewellery/pendants/$slug'
    | '/jewellery/rings/$slug'
    | '/jewellery/watches/$slug'
    | '/bags/gym-bags'
    | '/bags/handbags'
    | '/bags/party-bags'
    | '/bags/potli-bags'
    | '/bags/shoulder-bags'
    | '/bags/travel-bags'
    | '/clutches/bridal'
    | '/clutches/designer'
    | '/clutches/party'
    | '/clutches/potli'
    | '/jewellery/bracelets'
    | '/jewellery/earrings'
    | '/jewellery/jewellery-sets'
    | '/jewellery/necklaces'
    | '/jewellery/pendants'
    | '/jewellery/rings'
    | '/jewellery/watches'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/best-sellers'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/new-arrivals'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/sitemap.xml'
    | '/terms'
    | '/wishlist'
    | '/order/$reference'
    | '/admin/'
    | '/bags/'
    | '/clutches/'
    | '/jewellery/'
    | '/bags/gym-bags/$slug'
    | '/bags/handbags/$slug'
    | '/bags/party-bags/$slug'
    | '/bags/potli-bags/$slug'
    | '/bags/shoulder-bags/$slug'
    | '/bags/travel-bags/$slug'
    | '/clutches/bridal/$slug'
    | '/clutches/designer/$slug'
    | '/clutches/party/$slug'
    | '/clutches/potli/$slug'
    | '/jewellery/bracelets/$slug'
    | '/jewellery/earrings/$slug'
    | '/jewellery/jewellery-sets/$slug'
    | '/jewellery/necklaces/$slug'
    | '/jewellery/pendants/$slug'
    | '/jewellery/rings/$slug'
    | '/jewellery/watches/$slug'
    | '/bags/gym-bags/'
    | '/bags/handbags/'
    | '/bags/party-bags/'
    | '/bags/potli-bags/'
    | '/bags/shoulder-bags/'
    | '/bags/travel-bags/'
    | '/clutches/bridal/'
    | '/clutches/designer/'
    | '/clutches/party/'
    | '/clutches/potli/'
    | '/jewellery/bracelets/'
    | '/jewellery/earrings/'
    | '/jewellery/jewellery-sets/'
    | '/jewellery/necklaces/'
    | '/jewellery/pendants/'
    | '/jewellery/rings/'
    | '/jewellery/watches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BestSellersRoute: typeof BestSellersRoute
  BlogRoute: typeof BlogRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  OrderReferenceRoute: typeof OrderReferenceRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BagsIndexRoute: typeof BagsIndexRoute
  ClutchesIndexRoute: typeof ClutchesIndexRoute
  JewelleryIndexRoute: typeof JewelleryIndexRoute
  BagsGymBagsSlugRoute: typeof BagsGymBagsSlugRoute
  BagsHandbagsSlugRoute: typeof BagsHandbagsSlugRoute
  BagsPartyBagsSlugRoute: typeof BagsPartyBagsSlugRoute
  BagsPotliBagsSlugRoute: typeof BagsPotliBagsSlugRoute
  BagsShoulderBagsSlugRoute: typeof BagsShoulderBagsSlugRoute
  BagsTravelBagsSlugRoute: typeof BagsTravelBagsSlugRoute
  ClutchesBridalSlugRoute: typeof ClutchesBridalSlugRoute
  ClutchesDesignerSlugRoute: typeof ClutchesDesignerSlugRoute
  ClutchesPartySlugRoute: typeof ClutchesPartySlugRoute
  ClutchesPotliSlugRoute: typeof ClutchesPotliSlugRoute
  JewelleryBraceletsSlugRoute: typeof JewelleryBraceletsSlugRoute
  JewelleryEarringsSlugRoute: typeof JewelleryEarringsSlugRoute
  JewelleryJewellerySetsSlugRoute: typeof JewelleryJewellerySetsSlugRoute
  JewelleryNecklacesSlugRoute: typeof JewelleryNecklacesSlugRoute
  JewelleryPendantsSlugRoute: typeof JewelleryPendantsSlugRoute
  JewelleryRingsSlugRoute: typeof JewelleryRingsSlugRoute
  JewelleryWatchesSlugRoute: typeof JewelleryWatchesSlugRoute
  BagsGymBagsIndexRoute: typeof BagsGymBagsIndexRoute
  BagsHandbagsIndexRoute: typeof BagsHandbagsIndexRoute
  BagsPartyBagsIndexRoute: typeof BagsPartyBagsIndexRoute
  BagsPotliBagsIndexRoute: typeof BagsPotliBagsIndexRoute
  BagsShoulderBagsIndexRoute: typeof BagsShoulderBagsIndexRoute
  BagsTravelBagsIndexRoute: typeof BagsTravelBagsIndexRoute
  ClutchesBridalIndexRoute: typeof ClutchesBridalIndexRoute
  ClutchesDesignerIndexRoute: typeof ClutchesDesignerIndexRoute
  ClutchesPartyIndexRoute: typeof ClutchesPartyIndexRoute
  ClutchesPotliIndexRoute: typeof ClutchesPotliIndexRoute
  JewelleryBraceletsIndexRoute: typeof JewelleryBraceletsIndexRoute
  JewelleryEarringsIndexRoute: typeof JewelleryEarringsIndexRoute
  JewelleryJewellerySetsIndexRoute: typeof JewelleryJewellerySetsIndexRoute
  JewelleryNecklacesIndexRoute: typeof JewelleryNecklacesIndexRoute
  JewelleryPendantsIndexRoute: typeof JewelleryPendantsIndexRoute
  JewelleryRingsIndexRoute: typeof JewelleryRingsIndexRoute
  JewelleryWatchesIndexRoute: typeof JewelleryWatchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-sellers': {
      id: '/best-sellers'
      path: '/best-sellers'
      fullPath: '/best-sellers'
      preLoaderRoute: typeof BestSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/': {
      id: '/bags/'
      path: '/bags'
      fullPath: '/bags/'
      preLoaderRoute: typeof BagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clutches/': {
      id: '/clutches/'
      path: '/clutches'
      fullPath: '/clutches/'
      preLoaderRoute: typeof ClutchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/': {
      id: '/jewellery/'
      path: '/jewellery'
      fullPath: '/jewellery/'
      preLoaderRoute: typeof JewelleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$reference': {
      id: '/order/$reference'
      path: '/order/$reference'
      fullPath: '/order/$reference'
      preLoaderRoute: typeof OrderReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/gym-bags/': {
      id: '/bags/gym-bags/'
      path: '/bags/gym-bags'
      fullPath: '/bags/gym-bags/'
      preLoaderRoute: typeof BagsGymBagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/gym-bags/$slug': {
      id: '/bags/gym-bags/$slug'
      path: '/bags/gym-bags/$slug'
      fullPath: '/bags/gym-bags/$slug'
      preLoaderRoute: typeof BagsGymBagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/handbags/': {
      id: '/bags/handbags/'
      path: '/bags/handbags'
      fullPath: '/bags/handbags/'
      preLoaderRoute: typeof BagsHandbagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/handbags/$slug': {
      id: '/bags/handbags/$slug'
      path: '/bags/handbags/$slug'
      fullPath: '/bags/handbags/$slug'
      preLoaderRoute: typeof BagsHandbagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/party-bags/': {
      id: '/bags/party-bags/'
      path: '/bags/party-bags'
      fullPath: '/bags/party-bags/'
      preLoaderRoute: typeof BagsPartyBagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/party-bags/$slug': {
      id: '/bags/party-bags/$slug'
      path: '/bags/party-bags/$slug'
      fullPath: '/bags/party-bags/$slug'
      preLoaderRoute: typeof BagsPartyBagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/potli-bags/': {
      id: '/bags/potli-bags/'
      path: '/bags/potli-bags'
      fullPath: '/bags/potli-bags/'
      preLoaderRoute: typeof BagsPotliBagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/potli-bags/$slug': {
      id: '/bags/potli-bags/$slug'
      path: '/bags/potli-bags/$slug'
      fullPath: '/bags/potli-bags/$slug'
      preLoaderRoute: typeof BagsPotliBagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/shoulder-bags/': {
      id: '/bags/shoulder-bags/'
      path: '/bags/shoulder-bags'
      fullPath: '/bags/shoulder-bags/'
      preLoaderRoute: typeof BagsShoulderBagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/shoulder-bags/$slug': {
      id: '/bags/shoulder-bags/$slug'
      path: '/bags/shoulder-bags/$slug'
      fullPath: '/bags/shoulder-bags/$slug'
      preLoaderRoute: typeof BagsShoulderBagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/travel-bags/': {
      id: '/bags/travel-bags/'
      path: '/bags/travel-bags'
      fullPath: '/bags/travel-bags/'
      preLoaderRoute: typeof BagsTravelBagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bags/travel-bags/$slug': {
      id: '/bags/travel-bags/$slug'
      path: '/bags/travel-bags/$slug'
      fullPath: '/bags/travel-bags/$slug'
      preLoaderRoute: typeof BagsTravelBagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clutches/bridal/': {
      id: '/clutches/bridal/'
      path: '/clutches/bridal'
      fullPath: '/clutches/bridal/'
      preLoaderRoute: typeof ClutchesBridalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clutches/bridal/$slug': {
      id: '/clutches/bridal/$slug'
      path: '/clutches/bridal/$slug'
      fullPath: '/clutches/bridal/$slug'
      preLoaderRoute: typeof ClutchesBridalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clutches/designer/': {
      id: '/clutches/designer/'
      path: '/clutches/designer'
      fullPath: '/clutches/designer/'
      preLoaderRoute: typeof ClutchesDesignerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clutches/designer/$slug': {
      id: '/clutches/designer/$slug'
      path: '/clutches/designer/$slug'
      fullPath: '/clutches/designer/$slug'
      preLoaderRoute: typeof ClutchesDesignerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clutches/party/': {
      id: '/clutches/party/'
      path: '/clutches/party'
      fullPath: '/clutches/party/'
      preLoaderRoute: typeof ClutchesPartyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clutches/party/$slug': {
      id: '/clutches/party/$slug'
      path: '/clutches/party/$slug'
      fullPath: '/clutches/party/$slug'
      preLoaderRoute: typeof ClutchesPartySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clutches/potli/': {
      id: '/clutches/potli/'
      path: '/clutches/potli'
      fullPath: '/clutches/potli/'
      preLoaderRoute: typeof ClutchesPotliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clutches/potli/$slug': {
      id: '/clutches/potli/$slug'
      path: '/clutches/potli/$slug'
      fullPath: '/clutches/potli/$slug'
      preLoaderRoute: typeof ClutchesPotliSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/bracelets/': {
      id: '/jewellery/bracelets/'
      path: '/jewellery/bracelets'
      fullPath: '/jewellery/bracelets/'
      preLoaderRoute: typeof JewelleryBraceletsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/bracelets/$slug': {
      id: '/jewellery/bracelets/$slug'
      path: '/jewellery/bracelets/$slug'
      fullPath: '/jewellery/bracelets/$slug'
      preLoaderRoute: typeof JewelleryBraceletsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/earrings/': {
      id: '/jewellery/earrings/'
      path: '/jewellery/earrings'
      fullPath: '/jewellery/earrings/'
      preLoaderRoute: typeof JewelleryEarringsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/earrings/$slug': {
      id: '/jewellery/earrings/$slug'
      path: '/jewellery/earrings/$slug'
      fullPath: '/jewellery/earrings/$slug'
      preLoaderRoute: typeof JewelleryEarringsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/jewellery-sets/': {
      id: '/jewellery/jewellery-sets/'
      path: '/jewellery/jewellery-sets'
      fullPath: '/jewellery/jewellery-sets/'
      preLoaderRoute: typeof JewelleryJewellerySetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/jewellery-sets/$slug': {
      id: '/jewellery/jewellery-sets/$slug'
      path: '/jewellery/jewellery-sets/$slug'
      fullPath: '/jewellery/jewellery-sets/$slug'
      preLoaderRoute: typeof JewelleryJewellerySetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/necklaces/': {
      id: '/jewellery/necklaces/'
      path: '/jewellery/necklaces'
      fullPath: '/jewellery/necklaces/'
      preLoaderRoute: typeof JewelleryNecklacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/necklaces/$slug': {
      id: '/jewellery/necklaces/$slug'
      path: '/jewellery/necklaces/$slug'
      fullPath: '/jewellery/necklaces/$slug'
      preLoaderRoute: typeof JewelleryNecklacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/pendants/': {
      id: '/jewellery/pendants/'
      path: '/jewellery/pendants'
      fullPath: '/jewellery/pendants/'
      preLoaderRoute: typeof JewelleryPendantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/pendants/$slug': {
      id: '/jewellery/pendants/$slug'
      path: '/jewellery/pendants/$slug'
      fullPath: '/jewellery/pendants/$slug'
      preLoaderRoute: typeof JewelleryPendantsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/rings/': {
      id: '/jewellery/rings/'
      path: '/jewellery/rings'
      fullPath: '/jewellery/rings/'
      preLoaderRoute: typeof JewelleryRingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/rings/$slug': {
      id: '/jewellery/rings/$slug'
      path: '/jewellery/rings/$slug'
      fullPath: '/jewellery/rings/$slug'
      preLoaderRoute: typeof JewelleryRingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/watches/': {
      id: '/jewellery/watches/'
      path: '/jewellery/watches'
      fullPath: '/jewellery/watches/'
      preLoaderRoute: typeof JewelleryWatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery/watches/$slug': {
      id: '/jewellery/watches/$slug'
      path: '/jewellery/watches/$slug'
      fullPath: '/jewellery/watches/$slug'
      preLoaderRoute: typeof JewelleryWatchesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BestSellersRoute: BestSellersRoute,
  BlogRoute: BlogRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  OrderReferenceRoute: OrderReferenceRoute,
  AdminIndexRoute: AdminIndexRoute,
  BagsIndexRoute: BagsIndexRoute,
  ClutchesIndexRoute: ClutchesIndexRoute,
  JewelleryIndexRoute: JewelleryIndexRoute,
  BagsGymBagsSlugRoute: BagsGymBagsSlugRoute,
  BagsHandbagsSlugRoute: BagsHandbagsSlugRoute,
  BagsPartyBagsSlugRoute: BagsPartyBagsSlugRoute,
  BagsPotliBagsSlugRoute: BagsPotliBagsSlugRoute,
  BagsShoulderBagsSlugRoute: BagsShoulderBagsSlugRoute,
  BagsTravelBagsSlugRoute: BagsTravelBagsSlugRoute,
  ClutchesBridalSlugRoute: ClutchesBridalSlugRoute,
  ClutchesDesignerSlugRoute: ClutchesDesignerSlugRoute,
  ClutchesPartySlugRoute: ClutchesPartySlugRoute,
  ClutchesPotliSlugRoute: ClutchesPotliSlugRoute,
  JewelleryBraceletsSlugRoute: JewelleryBraceletsSlugRoute,
  JewelleryEarringsSlugRoute: JewelleryEarringsSlugRoute,
  JewelleryJewellerySetsSlugRoute: JewelleryJewellerySetsSlugRoute,
  JewelleryNecklacesSlugRoute: JewelleryNecklacesSlugRoute,
  JewelleryPendantsSlugRoute: JewelleryPendantsSlugRoute,
  JewelleryRingsSlugRoute: JewelleryRingsSlugRoute,
  JewelleryWatchesSlugRoute: JewelleryWatchesSlugRoute,
  BagsGymBagsIndexRoute: BagsGymBagsIndexRoute,
  BagsHandbagsIndexRoute: BagsHandbagsIndexRoute,
  BagsPartyBagsIndexRoute: BagsPartyBagsIndexRoute,
  BagsPotliBagsIndexRoute: BagsPotliBagsIndexRoute,
  BagsShoulderBagsIndexRoute: BagsShoulderBagsIndexRoute,
  BagsTravelBagsIndexRoute: BagsTravelBagsIndexRoute,
  ClutchesBridalIndexRoute: ClutchesBridalIndexRoute,
  ClutchesDesignerIndexRoute: ClutchesDesignerIndexRoute,
  ClutchesPartyIndexRoute: ClutchesPartyIndexRoute,
  ClutchesPotliIndexRoute: ClutchesPotliIndexRoute,
  JewelleryBraceletsIndexRoute: JewelleryBraceletsIndexRoute,
  JewelleryEarringsIndexRoute: JewelleryEarringsIndexRoute,
  JewelleryJewellerySetsIndexRoute: JewelleryJewellerySetsIndexRoute,
  JewelleryNecklacesIndexRoute: JewelleryNecklacesIndexRoute,
  JewelleryPendantsIndexRoute: JewelleryPendantsIndexRoute,
  JewelleryRingsIndexRoute: JewelleryRingsIndexRoute,
  JewelleryWatchesIndexRoute: JewelleryWatchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
